version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

  database:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - app

  tests:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
