version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "ConnectionStrings__MyDatabase=Server=mySqlServer;Database=myDatabase;User=myUser;Password=myPassword;"

  tests:
    build:
      context: .
      dockerfile: Dockerfile